#!/bin/bash

send_message() {
  json_escape() {
    printf '%s' "$1" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))'
  }

  # Read the URL, and read and escape username and message,
  # from command line arguments (json_escape uses a teeny bit of python3).
  webhook_url="$1"
  message_username=$(json_escape "$2")
  message_content=$(json_escape "$3")

  # Construct a JSON object with those values
  json="{\"username\": $message_username, \"content\": $message_content}"

  # Send JSON to Discord using curl
  curl -H "Content-Type: application/json" \
    -X POST \
    -d "$json" "$webhook_url"
}
ProgressBar() {
  # Process data
  progress=("${1}" * 100 / "${2}" * 100)/100
  done=("$progress" * 4)/10
  left=40-$done
  # Build progressbar string lengths
  done=$(printf "%${done}s")
  left=$(printf "%${left}s")

  # 1.2 Build progressbar strings and print the ProgressBar line
  # 1.2.1 Output example (default prefix):
  # 1.2.1.1 Progress : [########################################] 100%
  # 1.2.2 Output example (alternate prefix):
  # 1.2.2.1 Disk Usage : [##############################          ] 90%
  printf "\r${3:-Progress} : [${done// /#}${left// /-}] ${progress}%%"

}
webhook_url='https://discord.com/api/webhooks/777511962074021908/a9JrnqpGKhLg6H7v8fVTADGtEOUyQc7k7-cpXuuRavuzWxptha3dL9ELJvTXvCG5ojM_'

DEBUGMODE=0

# Helper function for precise units
kb2gb() {
  echo "$1" "$2" | awk '{ foo = ($1 + $2) / 1024 / 1024 ; print foo }'
}

# Do some free space calculations with df and awk
dfk=$(df -k ~)
kbused=$(echo "$dfk" | awk 'NR == 2 { print $3 }')
kbfree=$(echo "$dfk" | awk 'NR == 2 { print $4 }')
gbtotal=$(kb2gb "$kbused" "$kbfree")
gbused=$(kb2gb "$kbused")
gbfree=$(kb2gb "$kbfree")
gbtotali=$(printf "%.f\n" "$gbtotal")
gbusedi=$(printf "%.f\n" "$gbused")
gbusedf=$(printf "%'.3f\n" "$gbused")
gbfreef=$(printf "%'.3f\n" "$gbfree")
timestamp=$(TZ=America/New_York date +"%r")

# Make it into something readable with a fancy progress bar
read -r -d '' message <<EOM
\`\`\`
$(ProgressBar "$gbusedi" "$gbtotali" "$gbusedf GB Used")
$gbfreef GB Remaining [$timestamp EST]
\`\`\`
EOM

if [ $DEBUGMODE -eq 1 ]; then
  echo "Not sending message:"
  echo "$message"
else
  send_message "$webhook_url" "Disk Usage Report" "$message"
fi
